// Токены компонентов.
import { TDesignTokensComponents } from "./types/DesignTokensTypes";
import { ETriplexNextTheme } from "../ThemeProvider/ETriplexNextTheme";
import { GetTokensValueByTheme } from "./GetTokensValueByTheme";
import {
    AlertContext_Tokens,
    AlertProcess_Tokens,
    Avatar_Tokens,
    Badge_Tokens,
    Button_Tokens,
    Calendar_Tokens,
    Card_Tokens,
    Checkbox_Tokens,
    Chip_Tokens,
    Divider_Tokens,
    Dropdown_Tokens,
    DropdownList_Tokens,
    DropdownMobileList_Tokens,
    DropdownMobile_Tokens,
    FooterPage_Tokens,
    FormField_Tokens,
    HeaderPage_Tokens,
    Island_Tokens,
    IslandAccordion_Tokens,
    IslandWidget_Tokens,
    LightBox_Tokens,
    Link_Tokens,
    ListItemControlsButton_Tokens,
    ListItem_Tokens,
    ListMaster_Tokens,
    Loader_Tokens,
    LoaderScreen_Tokens,
    Marker_Tokens,
    MarkerStatus_Tokens,
    ModalWindow_Tokens,
    MultiselectField_Tokens,
    Notification_Tokens,
    Overlay_Tokens,
    Pagination_Tokens,
    Radio_Tokens,
    SegmentedControlSegment_Tokens,
    SegmentedControl_Tokens,
    Skeleton_Tokens,
    SmallInput_Tokens,
    SMSField_Tokens,
    Slider_Tokens,
    StatusTracker_Tokens,
    Step_Tokens,
    Stepper_Tokens,
    TableBasic_Tokens,
    TabsLine_Tokens,
    Tabs_Tokens,
    Tag_Tokens,
    TagColor_Tokens,
    Typography_Tokens,
    Tooltip_Tokens,
    TopOverlay_Tokens,
    UploadZone_Tokens,
    TDesignTokensComponentsAlertContextValue,
    TDesignTokensComponentsAlertProcessValue,
    TDesignTokensComponentsAvatarValue,
    TDesignTokensComponentsBadgeValue,
    TDesignTokensComponentsButtonValue,
    TDesignTokensComponentsCalendarValue,
    TDesignTokensComponentsCardValue,
    TDesignTokensComponentsCheckboxValue,
    TDesignTokensComponentsChipValue,
    TDesignTokensComponentsDividerValue,
    TDesignTokensComponentsDropdownListValue,
    TDesignTokensComponentsDropdownMobileListValue,
    TDesignTokensComponentsDropdownMobileValue,
    TDesignTokensComponentsDropdownValue,
    TDesignTokensComponentsFooterPageValue,
    TDesignTokensComponentsFormFieldValue,
    TDesignTokensComponentsHeaderPageValue,
    TDesignTokensComponentsIslandValue,
    TDesignTokensComponentsIslandAccordionValue,
    TDesignTokensComponentsIslandWidgetValue,
    TDesignTokensComponentsLightBoxValue,
    TDesignTokensComponentsLinkValue,
    TDesignTokensComponentsListItemControlsButtonValue,
    TDesignTokensComponentsListItemValue,
    TDesignTokensComponentsListMasterValue,
    TDesignTokensComponentsLoaderValue,
    TDesignTokensComponentsLoaderScreenValue,
    TDesignTokensComponentsMarkerValue,
    TDesignTokensComponentsMarkerStatusValue,
    TDesignTokensComponentsModalWindowValue,
    TDesignTokensComponentsMultiselectFieldValue,
    TDesignTokensComponentsNotificationValue,
    TDesignTokensComponentsOverlayValue,
    TDesignTokensComponentsPaginationValue,
    TDesignTokensComponentsRadioValue,
    TDesignTokensComponentsSegmentedControlSegmentValue,
    TDesignTokensComponentsSegmentedControlValue,
    TDesignTokensComponentsSkeletonValue,
    TDesignTokensComponentsSmallInputValue,
    TDesignTokensComponentsSMSFieldValue,
    TDesignTokensComponentsSliderValue,
    TDesignTokensComponentsStatusTrackerValue,
    TDesignTokensComponentsStepValue,
    TDesignTokensComponentsStepperValue,
    TDesignTokensComponentsTableBasicValue,
    TDesignTokensComponentsTabsLineValue,
    TDesignTokensComponentsTabsValue,
    TDesignTokensComponentsTagValue,
    TDesignTokensComponentsTagColorValue,
    TDesignTokensComponentsTooltipValue,
    TDesignTokensComponentsTopOverlayValue,
    TDesignTokensComponentsTypographyValue,
    TDesignTokensComponentsUploadZoneValue,
} from "./components";

export const DesignTokensComponents: TDesignTokensComponents = {
    AlertContext: GetTokensValueByTheme<TDesignTokensComponentsAlertContextValue>(
        ETriplexNextTheme.LIGHT,
        AlertContext_Tokens,
    ),
    AlertProcess: GetTokensValueByTheme<TDesignTokensComponentsAlertProcessValue>(
        ETriplexNextTheme.LIGHT,
        AlertProcess_Tokens,
    ),
    Avatar: GetTokensValueByTheme<TDesignTokensComponentsAvatarValue>(ETriplexNextTheme.LIGHT, Avatar_Tokens),
    Badge: GetTokensValueByTheme<TDesignTokensComponentsBadgeValue>(ETriplexNextTheme.LIGHT, Badge_Tokens),
    Button: GetTokensValueByTheme<TDesignTokensComponentsButtonValue>(ETriplexNextTheme.LIGHT, Button_Tokens),
    Calendar: GetTokensValueByTheme<TDesignTokensComponentsCalendarValue>(ETriplexNextTheme.LIGHT, Calendar_Tokens),
    Card: GetTokensValueByTheme<TDesignTokensComponentsCardValue>(ETriplexNextTheme.LIGHT, Card_Tokens),
    Checkbox: GetTokensValueByTheme<TDesignTokensComponentsCheckboxValue>(ETriplexNextTheme.LIGHT, Checkbox_Tokens),
    Chip: GetTokensValueByTheme<TDesignTokensComponentsChipValue>(ETriplexNextTheme.LIGHT, Chip_Tokens),
    Divider: GetTokensValueByTheme<TDesignTokensComponentsDividerValue>(ETriplexNextTheme.LIGHT, Divider_Tokens),
    Dropdown: GetTokensValueByTheme<TDesignTokensComponentsDropdownValue>(ETriplexNextTheme.LIGHT, Dropdown_Tokens),
    DropdownList: GetTokensValueByTheme<TDesignTokensComponentsDropdownListValue>(
        ETriplexNextTheme.LIGHT,
        DropdownList_Tokens,
    ),
    DropdownMobile: GetTokensValueByTheme<TDesignTokensComponentsDropdownMobileValue>(
        ETriplexNextTheme.LIGHT,
        DropdownMobile_Tokens,
    ),
    DropdownMobileList: GetTokensValueByTheme<TDesignTokensComponentsDropdownMobileListValue>(
        ETriplexNextTheme.LIGHT,
        DropdownMobileList_Tokens,
    ),
    FooterPage: GetTokensValueByTheme<TDesignTokensComponentsFooterPageValue>(
        ETriplexNextTheme.LIGHT,
        FooterPage_Tokens,
    ),
    FormField: GetTokensValueByTheme<TDesignTokensComponentsFormFieldValue>(ETriplexNextTheme.LIGHT, FormField_Tokens),
    HeaderPage: GetTokensValueByTheme<TDesignTokensComponentsHeaderPageValue>(
        ETriplexNextTheme.LIGHT,
        HeaderPage_Tokens,
    ),
    Island: GetTokensValueByTheme<TDesignTokensComponentsIslandValue>(ETriplexNextTheme.LIGHT, Island_Tokens),
    IslandAccordion: GetTokensValueByTheme<TDesignTokensComponentsIslandAccordionValue>(
        ETriplexNextTheme.LIGHT,
        IslandAccordion_Tokens,
    ),
    IslandWidget: GetTokensValueByTheme<TDesignTokensComponentsIslandWidgetValue>(
        ETriplexNextTheme.LIGHT,
        IslandWidget_Tokens,
    ),
    LightBox: GetTokensValueByTheme<TDesignTokensComponentsLightBoxValue>(ETriplexNextTheme.LIGHT, LightBox_Tokens),
    Link: GetTokensValueByTheme<TDesignTokensComponentsLinkValue>(ETriplexNextTheme.LIGHT, Link_Tokens),
    ListItem: GetTokensValueByTheme<TDesignTokensComponentsListItemValue>(ETriplexNextTheme.LIGHT, ListItem_Tokens),
    ListItemControlsButton: GetTokensValueByTheme<TDesignTokensComponentsListItemControlsButtonValue>(
        ETriplexNextTheme.LIGHT,
        ListItemControlsButton_Tokens,
    ),
    ListMaster: GetTokensValueByTheme<TDesignTokensComponentsListMasterValue>(
        ETriplexNextTheme.LIGHT,
        ListMaster_Tokens,
    ),
    Loader: GetTokensValueByTheme<TDesignTokensComponentsLoaderValue>(ETriplexNextTheme.LIGHT, Loader_Tokens),
    LoaderScreen: GetTokensValueByTheme<TDesignTokensComponentsLoaderScreenValue>(
        ETriplexNextTheme.LIGHT,
        LoaderScreen_Tokens,
    ),
    Marker: GetTokensValueByTheme<TDesignTokensComponentsMarkerValue>(ETriplexNextTheme.LIGHT, Marker_Tokens),
    MarkerStatus: GetTokensValueByTheme<TDesignTokensComponentsMarkerStatusValue>(
        ETriplexNextTheme.LIGHT,
        MarkerStatus_Tokens,
    ),
    ModalWindow: GetTokensValueByTheme<TDesignTokensComponentsModalWindowValue>(
        ETriplexNextTheme.LIGHT,
        ModalWindow_Tokens,
    ),
    MultiselectField: GetTokensValueByTheme<TDesignTokensComponentsMultiselectFieldValue>(
        ETriplexNextTheme.LIGHT,
        MultiselectField_Tokens,
    ),
    Notification: GetTokensValueByTheme<TDesignTokensComponentsNotificationValue>(
        ETriplexNextTheme.LIGHT,
        Notification_Tokens,
    ),
    Overlay: GetTokensValueByTheme<TDesignTokensComponentsOverlayValue>(ETriplexNextTheme.LIGHT, Overlay_Tokens),
    Pagination: GetTokensValueByTheme<TDesignTokensComponentsPaginationValue>(
        ETriplexNextTheme.LIGHT,
        Pagination_Tokens,
    ),
    Radio: GetTokensValueByTheme<TDesignTokensComponentsRadioValue>(ETriplexNextTheme.LIGHT, Radio_Tokens),
    SegmentedControl: GetTokensValueByTheme<TDesignTokensComponentsSegmentedControlValue>(
        ETriplexNextTheme.LIGHT,
        SegmentedControl_Tokens,
    ),
    SegmentedControlSegment: GetTokensValueByTheme<TDesignTokensComponentsSegmentedControlSegmentValue>(
        ETriplexNextTheme.LIGHT,
        SegmentedControlSegment_Tokens,
    ),
    Skeleton: GetTokensValueByTheme<TDesignTokensComponentsSkeletonValue>(ETriplexNextTheme.LIGHT, Skeleton_Tokens),
    SmallInput: GetTokensValueByTheme<TDesignTokensComponentsSmallInputValue>(
        ETriplexNextTheme.LIGHT,
        SmallInput_Tokens,
    ),
    SMSField: GetTokensValueByTheme<TDesignTokensComponentsSMSFieldValue>(ETriplexNextTheme.LIGHT, SMSField_Tokens),
    Slider: GetTokensValueByTheme<TDesignTokensComponentsSliderValue>(ETriplexNextTheme.LIGHT, Slider_Tokens),
    StatusTracker: GetTokensValueByTheme<TDesignTokensComponentsStatusTrackerValue>(
        ETriplexNextTheme.LIGHT,
        StatusTracker_Tokens,
    ),
    Step: GetTokensValueByTheme<TDesignTokensComponentsStepValue>(ETriplexNextTheme.LIGHT, Step_Tokens),
    Stepper: GetTokensValueByTheme<TDesignTokensComponentsStepperValue>(ETriplexNextTheme.LIGHT, Stepper_Tokens),
    TableBasic: GetTokensValueByTheme<TDesignTokensComponentsTableBasicValue>(
        ETriplexNextTheme.LIGHT,
        TableBasic_Tokens,
    ),
    Tabs: GetTokensValueByTheme<TDesignTokensComponentsTabsValue>(ETriplexNextTheme.LIGHT, Tabs_Tokens),
    Tag: GetTokensValueByTheme<TDesignTokensComponentsTagValue>(ETriplexNextTheme.LIGHT, Tag_Tokens),
    TagColor: GetTokensValueByTheme<TDesignTokensComponentsTagColorValue>(ETriplexNextTheme.LIGHT, TagColor_Tokens),
    TabsLine: GetTokensValueByTheme<TDesignTokensComponentsTabsLineValue>(ETriplexNextTheme.LIGHT, TabsLine_Tokens),
    Tooltip: GetTokensValueByTheme<TDesignTokensComponentsTooltipValue>(ETriplexNextTheme.LIGHT, Tooltip_Tokens),
    TopOverlay: GetTokensValueByTheme<TDesignTokensComponentsTopOverlayValue>(
        ETriplexNextTheme.LIGHT,
        TopOverlay_Tokens,
    ),
    Typography: GetTokensValueByTheme<TDesignTokensComponentsTypographyValue>(
        ETriplexNextTheme.LIGHT,
        Typography_Tokens,
    ),
    UploadZone: GetTokensValueByTheme<TDesignTokensComponentsUploadZoneValue>(
        ETriplexNextTheme.LIGHT,
        UploadZone_Tokens,
    ),
};
